---
title: "Final"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(mapview)
library(sf)
library(StatMatch)
library(leaflet)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

```{r, include = F}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

```{r, include = F}
census_race_categories <- 
  c(
    "White Alone",
    "Black or African American",
    "American Indian and Alaska Native Alone",
    "Asian Alone",
    "Native Hawaiian and Other Pacific Islander Alone",
    "Some Other Race Alone",
    "Two or More Races"
  )

income_race <-
  1:7 %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2019,
      region = "county:001",
      regionin = "state:06",
      vars = paste0("group(C15002",LETTERS[x],")")
    ) %>%
      select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
      pivot_longer(
        ends_with("E"),
        names_to = "name",
        values_to = "estimate"
      ) %>%
      left_join(
        acs_vars_2019_5yr %>% 
          select(name, label)
      ) %>% 
      select(-name) %>% 
      separate(
        label,
        into = c(NA,NA,"sex", "education"),
        sep = "!!"
      ) %>% 
      filter(!is.na(education)) %>% 
      mutate(race = census_race_categories[x]) %>% 
      group_by(education, race) %>% 
      summarize(estimate = sum(estimate))
  })



```

retry 
```{r}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

ca_tracts <- tracts("CA", bay_county_names[1:9], cb = T, progress_bar = F)

bay_tract_race_income <- 
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "tract:*",
    regionin = "state:06+county:001,013,041,055,075,081,085,095,097",
    vars = c(
      "B19001_001E",
      "B19001_014E",
      "B19001_015E",
      "B19001_016E",
      "B19001_017E",
      "B19001A_001E"
    )
  ) %>% 
  transmute(
    tract = paste0(state, county, tract),
    perc_over100k = (B19001_014E + B19001_015E + B19001_016E + B19001_017E) / B19001_001E,
    perc_white = B19001A_001E / B19001_001E
  ) %>% 
  filter(
    !is.na(perc_over100k),
    !is.na(perc_white)
  ) %>% 
  left_join(
    ca_tracts %>% 
      select(GEOID),
    by = c("tract" = "GEOID")
  ) %>% 
  st_as_sf()

ca_counties <- counties("CA", cb = T, progress_bar = F)

urban_counties <- counties("CA", cb = T, progress_bar = F) %>% 
  filter(NAME %in% c("Alameda", "San Francisco"))

urban_cities <- 
  places("CA", cb = T, progress_bar = FALSE) %>% 
  filter(NAME %in% c("Oakland", "San Francisco", "San Jose","Fremont", "Santa Rosa", "Hayward", "Sunnyvale", "Santa Clara", "Vallejo", "Concord", "Berkeley"))

mapview(bay_tract_race_income) + mapview(urban_cities)



```







