---
title: "ChrisEscobedo_A2"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```


```{r}
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(mapview)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

2020 blocks are larger in the Oakland area, so 2020 was used for the shapefiles.

```{r}
oakland_boundary <- 
  places("CA", cb = T, progress_bar = FALSE) %>% 
  filter(NAME == "Oakland")
  
mapview(oakland_boundary, alpha.regions = 0.1)

alameda_blocks <- 
  blocks("CA", county = 001, year = 2020) %>% 
  mutate(
    GEOID = GEOID20
  )


blocks_within_oakland <-
  alameda_blocks %>% 
  st_centroid() %>% 
  .[oakland_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(alameda_blocks %>% select(GEOID)) %>% 
  st_as_sf()


alameda_blocks_2010 <- 
  blocks("CA", county = 001, year = 2010) %>% 
  mutate(
    GEOID = GEOID10
  )

blocks_within_oakland_2010 <-
  alameda_blocks_2010 %>% 
  st_centroid() %>% 
  .[oakland_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(alameda_blocks_2010 %>% select(GEOID)) %>% 
  st_as_sf()



mapview(blocks_within_oakland, alpha.regions = 0.1) + mapview(oakland_boundary, alpha.regions = 0)


oakland_blocks_all <- blocks_within_oakland[blocks_within_oakland_2010, ]


oakland_blocks_area <-
  oakland_blocks_all %>% 
  st_transform(26910) %>% 
  mutate(area = st_area(.))

oakland_blocks_intersection <-
  oakland_blocks_area %>% 
  st_intersection(
    blocks_within_oakland %>% 
      st_transform(26910)
  )
  
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = blocks_within_oakland_2010,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = oakland_blocks_intersection %>% 
      st_transform(4269),
    color = "red",
    weight = 0.75,
    fill = F
  )

dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

alameda_pop_race_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:001",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

alameda_pop_race_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:001",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

combined_oakland_blocks <-
  oakland_blocks_all %>% 
  select(block = GEOID) %>% 
  left_join(alameda_pop_race_2020) %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
    oakland_blocks_2010 %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area,
    pop = pop * perc_area
  )

population_2010

```



Reflect on your findings. Explain any key assumptions you made in the analysis, or caveats about the data sources that you think the reader should be aware of. 