---
output: html_document
editor_options: 
  chunk_output_type: console
---
---title: "Example 1"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = F, message = F)
```

```{r}
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

```{r}

year <- 2020
quarters <- 1:4
type <- "Electric"

pge_20_elec <- NULL

for(quarter in quarters){
  
  filename <- 
    paste0(
      "pge/PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )
  
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_20_elec <- rbind(pge_20_elec,temp)
  
  saveRDS(pge_20_elec, "pge_20_elec.rds")
}
```

```{r}
pge_filter <- filter(pge_20_elec, CUSTOMERCLASS %in% c("Elec- Residential","Elec- Commercial"))

names(pge_filter)
head(pge_filter)
pge_filter[1,1]
pge_filter[1:5,c("ZIPCODE")]
pge_filter[1:5, ]$CUSTOMERCLASS

pge_select <- 
  select(
    pge_filter, 
    !c(YEAR, COMBINED, AVERAGEKWH)
  )

pge_group <- 
  group_by(
    pge_select,
    MONTH,
    CUSTOMERCLASS
  )

pge_summarize <-
  summarize(
    pge_group,
    TOTALKWH =
      sum(
        TOTALKWH,
        na.rm = T
      ),
    TOTALCUSTOMERS =
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      )
  )

pge_mutate <-
  mutate(
    pge_summarize,
    AVERAGEKWH = 
      TOTALKWH/TOTALCUSTOMERS
  )

pge_20_elec <- pge_mutate

pge_wide <-
  pivot_wider(
    pge_summarize,
    names_from = CUSTOMERCLASS,
    values_from = TOTALKWH
  )

pge_wide

pge_tidy <-
  pivot_longer(
    pge_wide,
    c("Elec- Commercial", "Elec- Residential"),
    names_to = "CUSTOMERCLASS",
    values_to = "TOTALKWH"
  )


plot_ly() %>% 
  add_trace(
    data = pge_mutate %>% filter(CUSTOMERCLASS == "Elec- Residential"),
    x = ~MONTH,
    y = ~TOTALKWH,
    type = "bar",
    name = "Residential"
  ) %>% 
  add_trace(
    data = pge_mutate %>% filter(CUSTOMERCLASS == "Elec- Commercial"),
    x = ~MONTH,
    y = ~TOTALKWH,
    type = "bar",
    name = "Commercial"
  ) %>% 
  layout(
    xaxis = list(
      title = "Month",
      fixedrange = T
    ),
    yaxis = list(
      title = "kWh",
      fixedrange = T
    ),
    barmode = "stack",
    legend = list(title = list(text = "Electricity Type"))
  ) %>% 
  config(displayModeBar = F)

```


```{r}
health_full <- read_csv("https://chronicdata.cdc.gov/api/views/cwsq-ngmh/rows.csv?accessType=DOWNLOAD")

health_ca <- filter(health_full, StateAbbr == "CA")


```

