---
title: "ChrisEscobedo_A1"
author: "Chris Escobedo"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```


```{r}
library(tidyverse)
library(plotly)
library(stringr)
library(lubridate)
```

```{r, message = F}
years <- 2017:2021
quarters <- 1:4
types <- c("Electric","Gas")

pge_full <- NULL

for(year in years){
  for(quarter in quarters){
    for(type in types){
      filename <- 
        paste0(
          "pge/PGE_",
          year,
          "_Q",
          quarter,
          "_",
          type,
          "UsageByZip.csv"
        )
      
      if(file.exists(filename)){
        temp <- read_csv(filename)
        if(type == "Electric"){
          ## mutate electric to BTU
          mutatedTemp <- 
            temp %>% 
            filter(
              CUSTOMERCLASS %in%
                c("Elec- Residential", "Elec- Commercial")
            ) %>% 
            group_by(MONTH, YEAR, CUSTOMERCLASS) %>% 
            summarize(
              TOTALKWH = 
                sum(
                  TOTALKWH,
                  na.rm = T
                )
            ) %>% 
            mutate(
                TOTALKBTU =
                  TOTALKWH * 3.412
            )
        } else {
          ## mutate gas to BTU
          mutatedTemp <- 
            temp %>% 
            filter(
              CUSTOMERCLASS %in%
                c("Gas- Residential", "Gas- Commercial")
            ) %>% 
            group_by(MONTH, YEAR, CUSTOMERCLASS) %>% 
            summarize(
              TOTALTHM = 
                sum(
                  TOTALTHM,
                  na.rm = T
                )
            ) %>% 
            mutate(
                TOTALKBTU =
                  TOTALTHM * 100,000
            )
        }
         pge_full <- rbind(pge_full,mutatedTemp)
         saveRDS(pge_full, "pge_full.rds")
      }
    }  
  }
}  
```

```{r}
pge_full_dates <- pge_full %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )




```

```{r}
pge_residential_chart <-
  pge_full_dates %>%
  filter(
    CUSTOMERCLASS %in% c("Elec- Residential", "Gas- Residential")
  ) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE,
      y = TOTALKBTU,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Year",
    y = "kBTU",
    title = "PG&E Territory Residential Electricity and Gas Usage, 2017-2021",
    fill = "Residential Power Type"
  )

pge_residential_chart %>% ggplotly()


pge_commercial_chart <-
  pge_full_dates %>%
  filter(
    CUSTOMERCLASS %in% c("Elec- Commercial", "Gas- Commercial")
  ) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE,
      y = TOTALKBTU,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
    labs(
    x = "Year",
    y = "kBTU",
    title = "PG&E Territory Commercial Electricity and Gas Usage, 2017-2021",
    fill = "Commercial Power Type"
  )
pge_commercial_chart %>% ggplotly()

```
Something to Note is that there appears to be no electricity usage, commercial or residential, at the beginning of 2020. There likely was a disruption to data collection that occured at this time due to the onset of the pandemic. 

Other than this disruption, it does not seem that there are major changes in average energy and gas useage over time.


