---
title: "Chapter_3"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document  
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(mapboxapi)
library(readxl)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")

mb_access_token("pk.eyJ1IjoiY2hyaXNjb2JlZG8iLCJhIjoiY2t5dWpuOWQwMW5yeTJ1bzdkb2xwNDhzdCJ9.bvKU0wmr5ZptXvmo6vxRkQ", install = T)

path <- "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/NHTS/nhts17-caltrans-tsdc-download/"
```

Class:

```{r}
pois <- st_read("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OSM/gis_osm_pois_a_free_1.shp")

## get counts
pois_summary <- pois %>% 
  st_drop_geometry() %>% 
  group_by(fclass) %>% 
  count() %>% 
  arrange(desc(n))

## Getting geography - transforming to pois coordinate
smc_boundary <- counties("CA") %>% 
  filter(NAME == "San Mateo") %>% 
  st_transform(st_crs(pois))

## filtering to geography
smc_pois <- pois %>% 
  .[smc_boundary, ] %>% 
  rename(amenity = fclass)

mapview(smc_pois, zcol = "amenity")

## filter to important amenities
pois_filter <- pois %>% 
  rename(amenity = fclass) %>% 
  filter(amenity %in% c(
    "park",
    "convenience",
    "restaurant",
    "supermarket",
    "library"
  ))

mapview(smc_pois_filter, zcol = "amenity")

## get block groups
smc_cbgs <- block_groups("CA","San Mateo")

## get North Fair Oaks
nfo_boundary <- places("CA") %>% 
  filter(NAME == "North Fair Oaks")

## filter block group data to NFO
nfo_cbgs <- smc_cbgs %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_cbgs %>% select(GEOID)) %>% 
  st_as_sf()

mapview(nfo_cbgs)

## getting isochrones
# isochrone <- mb_isochrone(
#   nfo_cbgs,
#   profile = "walking",
#   time = c(5,10,15)
# )

isochrone[1:3,] %>% mapview()

## important to save so you dont rerun this and use up credits
saveRDS(isochrone, "nfo_isochrones.rds")
isochrone <- readRDS("nfo_isochrones.rds")

## create master data sheet- all isochrones 
access_raw <- isochrone %>% 
  st_make_valid() %>% 
  st_join(pois_filter) %>% 
  st_drop_geometry() %>% 
  filter(!is.na(osm_id))
```

next step -> making ranks

```{r}
amenity_preference <- data.frame(
  amenity = c("park", "convenience", "restaurant", "supermarket", "library"),
  amenity_value = c(
    0.9,
    0.2,
    0.8,
    1,
    0.3
  ),
  amenity_quantity = c(
    2,
    1,
    40,
    4,
    1
  )
) %>% 
  mutate(
    amenity_decay = -log(0.5)/amenity_quantity
  )

mode_preference <- data.frame(
  mode = c(
    "walking",
    "biking",
    "driving"
  ),
  mode_value = c(
    1,
    0.6,
    0.5
  ),
  mode_reasonable = c(
    10,
    15,
    20
  )
) %>% 
  mutate(
    mode_decay = -log(0.5)/mode_reasonable
  )

## joining complete scores
complete_temp <- access_raw %>% 
  left_join(
    amenity_preference,
    by = "amenity"
  ) %>% 
  left_join(
    mode_preference,
    by = "mode"
  ) %>% 
  group_by(id, mode, amenity) %>% 
  arrange(time) %>% 
  mutate(
    amenity_rank = row_number() - 1
  ) %>% 
  ungroup()

## making a baseline hypothetical
complete_baseline <- data.frame(
  amenity = amenity_preference$amenity %>% 
    rep(amenity_preference$amenity_quantity)
) %>% 
  left_join(
    amenity_preference,
    by = "amenity"
  ) %>% 
  group_by(amenity) %>% 
  mutate(
    amenity_rank = row_number() - 1
  ) %>% 
  ungroup() %>% 
  mutate(
    score = amenity_value * exp(-amenity_rank * amenity_decay) * 0.5
  )

## baseline score
sum(complete_baseline$score)

## making complete modes
complete_modes <- complete_temp %>% 
  mutate(
    score = amenity_value * exp(-anenity_rank * amenity_decay) * exp(-time * mode_decay)
  ) %>% 
  group_by(id, mode) %>% 
  arrange(desc(score)) %>% 
  filter(!duplicated(osm_id)) %>% 
  summarize(
    score = sum(scores, na.rm = T) / sum(complete_baseline$score)
  )

## make a score
complete_total <- complete_temp %>% 
  mutate(
    score = amenity_value * exp(-amenity_rank * amenity_decay) * mode_value * exp(-time * mode_decay)
  ) %>% 
  group_by(id) %>% 
  arrange(desc(score)) %>% 
  filter(!duplicated(osm_id)) %>% 
  summarize(
    score = sum(scores, na.rm = T) / sum(complete_baseline$score)
  )

## make complete data frame
complete <- rbind(
  complete_modes,
  complete_total
) 

complete_map <- complete %>% 
  pivot_wider(
    names_from = "mode",
    values_from = "score"
  ) %>% 
  cbind(nfo_cbgs %>% select(GEOID)) %>% 
  st_as_sf

mapview(complete_map, zcol = "total")
```

isochrone example
```{r}
iscochrones <- NULL

for (x in c("walking", "driving")){
  
  temp <- mb_isochrone(
    nfo_cbgs,
    profile = x,
    time = c(5, 10, 15)
  ) %>% 
    mutate(
      mode = x
    )
  
  isochrones <- iscochrones %>% 
    rbind(temp)
}

## if doing too much, can use nested loops
isochrones <- NULL
  
for(x in c("walking","driving")){
    
  for(y in c(5,10,15)){
    
    for(z in 1:nrow(nfo_cbgs)){
      
      print(paste(x,y,z, sep = ","))
      
      temp <- mb_isochrone(
        nfo_cbgs[z,],
        profile = x,
        time = y
      ) %>% 
        mutate(mode = x)
      
      isochrones <- isochrones %>% 
        rbind(temp)
      
      if(z == 10) saveRDS(isochrones, "draft_isochrones.rds")
      
    }
  }
}
```



TEXTBOOK: 

3.1
```{r}
survey_household <- read_csv(paste0(path,"survey_household.csv"))

survey_person <- read.csv(paste0(path,"survey_person.csv")) 

survey_trip <- read_csv(paste0(path,"survey_trip.csv"))

survey_person_weights_7day <- read_csv(paste0(path,"survey_person_weights_7day.csv"))

nhts_lookup <- read_excel(
  paste0(path,"data_elements.xlsx"), 
  sheet = "Value Lookup"
)

## link weights to survey_person
person_weights <-
  survey_person %>% 
  left_join(
    survey_person_weights_7day %>% 
      select(
        sampno,
        perno,
        wttrdfin
      ),
    by = c("sampno","perno")
  )

## get geographies for bay area of CBSA's
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

cbsas <- core_based_statistical_areas(cb = T, progress_bar = F)

bay_cbsas <-
  cbsas %>%
  .[bay_counties %>% st_centroid(), ]

## map
leaflet(bay_cbsas) %>% 
  addTiles() %>% 
  addPolygons(
    label = ~paste0(GEOID,": ",NAME)
  )
```

fully combined dataset
```{r}
bay_trips <-
  survey_trip %>% 
  left_join(
    survey_person,
    by = c("sampno","perno")
  ) %>% 
  left_join(
    survey_person_weights_7day %>% 
      select(
        sampno,
        perno,
        wttrdfin
      ),
    by = c("sampno","perno")
  ) %>% 
  left_join(
    survey_household %>% select(
      sampno,
      hh_cbsa
    )
  ) %>% 
  filter(hh_cbsa %in% bay_cbsas$GEOID)

## look at trip purpose
purpose_lookup <-
  nhts_lookup %>% 
  filter(NAME == "WHYTO") %>% 
  select(VALUE, LABEL) %>% 
  mutate(
    VALUE = as.numeric(VALUE),
    LABEL = factor(LABEL, levels = LABEL)
  )

## look at mode
mode_lookup <-
  nhts_lookup %>% 
  filter(NAME == "TRPTRANS") %>% 
  select(VALUE, LABEL) %>% 
  mutate(
    VALUE = as.numeric(VALUE),
    LABEL = factor(LABEL, levels = LABEL)
  )
```

combining trip data
```{r}
bay_trips_summary_whyto <-
  bay_trips %>% 
  left_join(
    purpose_lookup,
    by = c("whyto" = "VALUE")
  ) %>% 
  rename(purpose_label = LABEL) %>% 
  left_join(
    mode_lookup,
    by = c("trptrans" = "VALUE")
  ) %>% 
  rename(mode_label = LABEL) %>% 
  mutate(
    tripmiles_wt =
      trpmiles * wttrdfin
  ) %>% 
  group_by(
    purpose_label,
    mode_label
  ) %>% 
  summarize(
    tripmiles_wt = sum(tripmiles_wt),
    trips = sum(wttrdfin)
  ) %>% 
  ungroup()

bay_trips_summary_whyfrom <-
  bay_trips %>% 
  left_join(
    purpose_lookup,
    by = c("whyfrom" = "VALUE")
  ) %>% 
  rename(purpose_label = LABEL) %>% 
  left_join(
    mode_lookup,
    by = c("trptrans" = "VALUE")
  ) %>% 
  rename(mode_label = LABEL) %>% 
  mutate(
    tripmiles_wt =
      trpmiles * wttrdfin
  ) %>% 
  group_by(
    purpose_label,
    mode_label
  ) %>% 
  summarize(
    tripmiles_wt = sum(tripmiles_wt),
    trips = sum(wttrdfin)
  ) %>% 
  ungroup()

bay_trips_summary <-
  rbind(
    bay_trips_summary_whyto,
    bay_trips_summary_whyfrom
  ) %>% 
  group_by(purpose_label, mode_label) %>% 
  summarize(
    tripmiles_wt = mean(tripmiles_wt, na.rm = T),
    trips = mean(trips, na.rm = T)
  ) %>% 
  ungroup()

## if you wanted data wide
bay_trips_summary_wide <-
  bay_trips_summary %>% 
  pivot_wider(
    -tripmiles_wt,
    names_from = mode_label,
    values_from = trips
  ) %>% 
  column_to_rownames("purpose_label")

## plot with refinements 
bay_trips_summary %>% 
  filter(
    trips > 1e6/2,
    !purpose_label %in% c("1. Regular home activities (chores, sleep)", "2. Work from home (paid)")
  ) %>% 
  ggplot(
    aes(
      x = purpose_label,
      y = reorder(mode_label, desc(mode_label))
    )
  ) +
  geom_tile(
    aes(fill = trips)
  ) + 
  geom_text(
    aes(label = (trips/1e6) %>% round()), 
    color = "white",
    size = 2
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(angle = 45, hjust = 1)
  ) + 
  labs(
    x = "Trip Purpose",
    y = "Trip Mode",
    title = "Bay Area travel patterns, 2017",
    subtitle = "Values are millions of trips per year. Trips are allocated based on 50/50 split\nof origin/destination purpose. Home-allocated trips removed."
  )

## percent plot
bay_trips_summary %>% 
  filter(
    !purpose_label %in% c("1. Regular home activities (chores, sleep)", "2. Work from home (paid)")
  ) %>% 
  mutate(
    trips_perc = trips/sum(trips)
  ) %>% 
  filter(
    trips_perc > 0.005
  ) %>% 
  ggplot(
    aes(
      x = purpose_label,
      y = reorder(mode_label, desc(mode_label))
    )
  ) +
  geom_tile(
    aes(fill = trips_perc)
  ) + 
  geom_text(
    aes(label = (trips_perc*100) %>% round()), 
    color = "white"
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(angle = 45, hjust = 1)
  ) + 
  labs(
    x = "Trip Purpose",
    y = "Trip Mode",
    title = "Bay Area travel patterns, 2017",
    subtitle = "Values are percent of trips per year. Trips are allocated based on 50/50 split\nof origin/destination purpose. Home-allocated trips removed."
  )

## trip miles plot - planes filtered out
bay_trips_summary %>% 
  filter(
    mode_label != "Airplane",
    !purpose_label %in% c("1. Regular home activities (chores, sleep)", "2. Work from home (paid)")
  ) %>% 
  mutate(
    tripmiles_perc = tripmiles_wt/sum(tripmiles_wt)
  ) %>%
  filter(
    tripmiles_perc > 0.005
  ) %>%
  ggplot(
    aes(
      x = purpose_label,
      y = reorder(mode_label, desc(mode_label))
    )
  ) +
  geom_tile(
    aes(fill = tripmiles_perc)
  ) + 
  geom_text(
    aes(label = (tripmiles_perc*100) %>% round()), 
    color = "white"
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(angle = 45, hjust = 1)
  ) + 
  labs(
    x = "Trip Destination",
    y = "Trip Mode",
    title = "Bay Area travel patterns, 2017",
    subtitle = "Values are percent of trip miles per year. Trips are allocated based on 50/50 split\nof origin/destination purpose. Home-allocated trips removed."
  )
```

3.4

```{r}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```


```{r}
covid_testing <-
  st_read("https://opendata.arcgis.com/datasets/d7d10caf1cec43e0985cc90fbbcf91cb_0.geojson")

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names) %>% 
  st_transform(st_crs(covid_testing))

bay_covid_testing <-
  covid_testing %>% 
  .[bay_counties, ] %>% 
  filter(status == "Open")

## map of covid test sites
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    data = bay_covid_testing,
    radius = 1,
    label = ~name
  )

## filter to santa clara county
scc_covid_testing <-
  bay_covid_testing %>% 
  .[bay_counties %>% filter(NAME == "Santa Clara"), ]

## isochrone
walk_10min <- mb_isochrone(
  scc_covid_testing,
  profile = "walking",
  time = 10
)

## bind to info
scc_covid_testing_walk_10min <-
  scc_covid_testing %>% 
  st_drop_geometry() %>% 
  cbind(walk_10min$geometry) %>% 
  st_as_sf()

leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>%
  addPolygons(
    data = scc_covid_testing_walk_10min,
    label = ~name
  )

## santa clara county block groups
scc_bgs <- 
  block_groups("CA","085", cb = T, progress_bar = F) %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.))

## intersecting isochrones (that are now combined to one geometry) with block groups
scc_bg_isochrone_intersect <-
  scc_bgs %>% 
  st_intersection(
    scc_covid_testing_walk_10min %>% 
      st_union() %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area
  )

## income data for santa clara block groups
scc_bg_income <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:085",
    vars = "group(B19001)"
  ) %>% 
  mutate(cbg = paste0(state,county,tract,block_group)) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"income"),
    sep = "!!"
  ) %>% 
  filter(!is.na(income)) %>% 
  mutate(
    income = case_when(
      income %in% c("Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999") ~ "Less than $25,000",
      income %in% c("$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999","$40,000 to $44,999","$45,000 to $49,999") ~ "$25,000 to $49,999",
      income %in% c("$50,000 to $59,999","$60,000 to $74,999") ~ "$50,000 to $74,999",
      TRUE ~ income
    )
  )

## block group info stats on income for all of Santa Clara
scc_income <-
  scc_bg_income %>% 
  mutate(income = factor(income, levels = unique(scc_bg_income$income))) %>% 
  group_by(income) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    perc = estimate/sum(estimate),
    group = "Full Population"
  )
  
## block group info stats for covid interections of isochrones in Santa Clara
scc_covid_income <-
  scc_bg_income %>% 
  mutate(income = factor(income, levels = unique(scc_bg_income$income))) %>% 
  left_join(
    scc_bg_isochrone_intersect %>% 
      select(cbg = GEOID, perc_area) %>% 
      st_drop_geometry()
  ) %>% 
  filter(!is.na(perc_area)) %>% 
  mutate(
    estimate = estimate * perc_area
  ) %>% 
  group_by(income) %>% 
  summarize(estimate = sum(estimate)) %>% 
  mutate(
    perc = estimate/sum(estimate),
    group = "Population within 10 min. walk of COVID-19 testing"
  )

## estimated percent of population in Santa Clara County within 10 minutes walk of COVID-19 testing.
sum(scc_covid_income$estimate)/
  sum(scc_income$estimate)

## equity analysis pie chart
rbind(scc_income,scc_covid_income) %>% 
  ggplot(
    aes(
      x = "", 
      y = perc, 
      fill = reorder(income,desc(income))
    )
  ) + 
  geom_bar(
    stat = "identity", 
    position = position_fill()
  ) +
  geom_text(
    aes(label = paste0(round(perc*100),"%")), 
    position = position_fill(vjust = 0.5)
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ group)  +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = 'bottom'
  ) + 
  guides(
    fill = guide_legend(nrow=3, byrow=TRUE)
  ) +
  labs(
    fill = "Household\nIncome"
  )
```

3.2

```{r}

```







