---
title: "Chapter4_Class"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(lehdr)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

## class:

```{r}
ca_od_read <- read_csv("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/LODES/ca_od_main_JT01_2019.csv.gz")

saveRDS(ca_od_read, "ca_od_main_2019.csv")

ca_od_read <- readRDS("ca_od_main_2019.csv")

zctas <- zctas()

zip <- zctas %>% 
  filter(GEOID10 == 94303)

blocks <- blocks("CA")

zip_blocks <- blocks %>% 
  st_centroid() %>% 
  .[zip, ]
  
zip_od <- ca_od_read %>% 
  filter(
    h_geocode %in% zip_blocks$GEOID10 |
      w_geocode %in% zip_blocks$GEOID10
  )

remove(ca_od_read)

full_zip_od <- 2013:2019 %>% 
  map_dfr(function(year){
    
    print(year)
    
    temp <- read_csv(paste0("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/LODES/ca_od_main_JT01_", year, ".csv.gz")) %>% 
      filter(
        h_geocode %in% zip_blocks$GEOID10 |
          w_geocode %in% zip_blocks$GEOID10
      ) %>% 
      mutate(year = year)
    
    saveRDS(temp, paste0("temp_od_", year, ".rds"))
    
    return(temp)
    
  })

full_zip_od <- readRDS("full_zip_od.rds")

## cleaning it by removing "negligible trips" - e.g. trips that went from one zip code to the same zip code - when blocks 
## are rounded to being the center of the zip code
full_zip_od_clean <- full_zip_od %>% 
  select(-createdate) %>% 
  filter(!(
    h_geocode %in% zip_blocks$GEOID10 &
      w_geocode %in% zip_blocks$GEOID10
  )) %>% 
  mutate(
    direction = ifelse(
      h_geocode %in% zip_blocks$GEOID10,
      "outbound",
      "inbound"
    )
  )
```

```{r}
full_zip_od_routing <- full_zip_od_clean %>% 
  mutate(
    origin = ifelse(
      direction == "inbound",
      h_geocode,
      w_geocode
    ),
    cbg = origin %>% substr(1,12),
    tract = origin %>% substr(1,11)
  ) %>% 
  filter(!duplicated(tract))

ca_tracts <- tracts("CA")

zip_od_origin <- 
  full_zip_od_routing %>% 
  select(tract) %>% 
  left_join(ca_tracts %>% select(tract = GEOID)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  st_coordinates()

zip_od_route <-
  1:nrow(zip_od_origin) %>% 
  map_dfr(function(x){
    
    tryCatch(
      mb_directions(
        origin = zip_od_origin[x, ],
        destination = zip_od_destination,
        profile = "driving-traffic"
      ) %>% 
      mutate(id = x),
      error = funtion(e){
        
      }
    )
    
  })
```



# Textbook:

```{r}
library(tigris)
library(tidyverse)
library(censusapi)
library(sf)
library(leaflet)
library(mapboxapi)
library(jsonlite)

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

sept21_patterns <- read_csv("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/Safegraph/Neighborhood_Patterns_Sept_2021/neighborhood_patterns.csv.gz")
```


```{r}

```

