---
title: "ChrisEscobedo_A4"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(lehdr)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(censusapi)
library(raster)
library(mapview)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

## Location

The analysis centered on Belle Haven, a historically under-resourced neighborhood in Menlo Park. The map below shows the three census block groups that make up the neighborhood and which will be used for the analysis. 

```{r, warning = F}
slr <- 25
rp <- 20

path <- paste0("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OCOF/san_mateo_flooding_slr",str_pad(slr, 3, "left", "0"), "/flooding/v2.1/county_san_mateo_flddepth_slr", str_pad(slr, 3, "left", "0"), "_w", str_pad(rp, 3, "left", "0"), ".tif")

test_flood <- raster(path)

# Belle Haven CBGs - 	060816117001,	060816117002, 060816117003
bh_boundary <- block_groups("CA", "San Mateo") %>% 
  filter(GEOID %in% c("060816117001",	"060816117002", "060816117003")) 

mapview(bh_boundary)
```


```{r, warning = F}

for(slr in c("000","025","050")){
  
  for(rp in c("001","020","100")){
    
    print(paste0("SLR",slr,"_RP",rp))
    
    path <- paste0("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OCOF/san_mateo_flooding_slr", slr, "/flooding/v2.1/county_san_mateo_flddepth_slr", slr, "_w", rp, ".tif")
    
    flood <- raster(path) %>% 
      crop(
        epa_boundary %>% 
          st_transform(26910) %>% 
          st_bbox()
      )
    
    writeRaster(flood, paste0("flood/SLR",slr,"_RP",rp,"_epa_flood.tif"), overwrite = T)
    
  }
}
```


```{r, warning = F}
flood_pal <- colorNumeric(
  palette = "Blues",
  domain = values(test_flood_bh),
  na.color = "transparent"
)

leaflet() %>% 
  addMapboxTiles(
    style_id = "satellite-streets-v11",
    username = "mapbox",
    options = tileOptions(opacity = 0.5)
  ) %>% 
  addRasterImage(
    test_flood_bh,
    colors = flood_pal
  ) %>% 
  addLegend(
    pal = flood_pal,
    values = values(test_flood_bh),
    title = "Flood depth, cm"
  )
```

