---
title: "ChrisEscobedo_A2"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document  
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(mapboxapi)
library(readxl)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")

mb_access_token("pk.eyJ1IjoiY2hyaXNjb2JlZG8iLCJhIjoiY2t5dWpuOWQwMW5yeTJ1bzdkb2xwNDhzdCJ9.bvKU0wmr5ZptXvmo6vxRkQ", install = T)

path <- "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/NHTS/nhts17-caltrans-tsdc-download/"
```

## Location

I choose North Richmond as a place to perform the equity analysis on the city completeness score becasue North Richmond is a particularly diverse area of one of the most diverse cities. It was also designated as an opportunity zone, which means that there is likely to be a need for investment in the area.

```{r}
cc_blocks <- blocks("CA","Contra Costa")

richmond_boundary <- places("CA") %>% 
  filter(NAME == "North Richmond")

richmond_blocks <- cc_blocks %>% 
  st_centroid() %>% 
  .[richmond_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(cc_blocks %>% select(GEOID10)) %>% 
  st_as_sf() %>% 
  filter(
    !(ALAND10 == 0)
  )

mapview(richmond_blocks)

## getting isochrones
# isochrones <- mb_isochrone(
#   richmond_blocks,
#   profile = "walking",
#   time = c(5,10,15)
# )  %>% 
#   mutate(
#     mode = "walking"
#   )
# 
# isochrones_cycling <- mb_isochrone(
#     richmond_blocks,
#     profile = "cycling",
#     time = c(5,10,15)
# )  %>% 
#   mutate(
#     mode = "biking"
#   )
# 
# isochrones_driving <- mb_isochrone(
#     richmond_blocks,
#     profile = "driving",
#     time = c(5,10,15)
# ) %>% 
#   mutate(
#     mode = "driving"
#   )
# 
# isochrones <- isochrones %>% 
#   rbind(isochrones_cycling) %>% 
#   rbind(isochrones_driving)
#
# saveRDS(isochrones, "richmond_isochrones.rds")

isochrones <- readRDS("richmond_isochrones.rds")

isochrones <- richmond_blocks %>% 
  mutate(
    id = 1:n()
  ) %>% 
  st_drop_geometry() %>% 
  select(id, GEOID10) %>% 
  left_join(isochrones)

isochrones <- readRDS("richmond_isochrones.rds")

mapview(isochrones) + mapview(richmond_blocks)
```



























