---
title: "A1_ChrisEscobedo"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document  
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(mapview)
library(tigris)
library(sf)
library(leaflet)
library(esri2sf)
library(tidycensus)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")

census_api_key("c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

ACS 5 Data

```{r}
EPA_boundary <- 
  places("CA", cb = T, progress_bar = FALSE) %>% 
  filter(NAME == "East Palo Alto")

getCensu

mapview(EPA_boundary)
```

Parcel Data

```{r}
epa_zoning <- esri2sf("https://services8.arcgis.com/0IC8hha3hgQkmGoa/arcgis/rest/services/EastPaloAltoZoning_2021_WFL1/FeatureServer/1")

smc_exemption <- read_csv("https://datahub.smcgov.org/api/views/pmvw-bs84/rows.csv?accessType=DOWNLOAD")

epa_exemption <- smc_exemption %>% 
  mutate(
    APN = `Parcel Number` %>% 
      str_replace_all("-","")
  ) %>% 
  filter(APN %in% epa_zoning$APN) %>% 
  left_join(epa_zoning) %>% 
  st_as_sf() %>% 
  filter(New_Zone == "R-LD")

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = epa_exemption %>% 
      filter(`Fiscal Year` == "2018/2019"),
    fillColor = "yellow",
    color = "black",
    weight = 0.5
  ) %>% 
  addPolygons(
    data = epa_exemption %>% 
      filter(Exemption %in% c(5600,7000)),
    fillColor = "blue",
    color = "black",
    weight = 0.5,
    fillOpacity = 1
  )

```


