---
title: "ChrisEscobedo_A5"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r global, include=FALSE}
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(censusapi)
library(mapview)
library(plotly)
library(jsonlite)
library(flexdashboard)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")

## PART 1 
# pa_api <- "F5058268-99B3-11EC-B9BF-42010A800003"
# 
# json <- fromJSON(paste0(
#     "https://api.purpleair.com/v1/sensors?api_key=",
#     pa_api,
#     "&fields=name,location_type,latitude,longitude,pm2.5_1week,temperature,humidity,primary_id_a,primary_key_a,secondary_id_a,secondary_key_a,primary_id_b,primary_key_b,secondary_id_b,secondary_key_b"
#   ))
# 
# all_sensors <- json %>% 
#   .$data %>% 
#   as.data.frame() %>% 
#   set_names(json$fields) %>% 
#   filter(
#     !is.na(longitude),
#     !is.na(latitude)
#   ) %>% 
#   st_as_sf(coords = c("longitude","latitude"), crs = 4326) %>% 
#   mutate(location_type = ifelse(
#     location_type == 0,
#     "outside",
#     "inside"
#   ))
# 
# smc_sensors <-
#   all_sensors %>%
#   .[counties("CA") %>% filter(NAME == "San Mateo") %>% st_transform(4326), ]
# 
# smc_sensors_clean <- smc_sensors %>% 
#   filter(
#     !is.na(pm2.5_1week),
#     !is.na(humidity)
#   ) %>% 
#   mutate(
#     PM25 = 0.524*as.numeric(pm2.5_1week) - 0.0852*as.numeric(humidity) + 5.72,
#     AQI = case_when(
#       PM25 <= 12 ~ 
#         paste(round(50/12*PM25), "Good"),
#       PM25 <= 35.4 ~ 
#         paste(round((100-51)/(35.4-12)*(PM25 - 12) + 51), "Moderate"),
#       PM25 <= 55.4 ~
#         paste(round((150-101)/(55.4-35.4)*(PM25 - 35.4) + 101), "Moderately Unhealthy"),
#       PM25 <= 150.4 ~
#         paste(round((200-151)/(150.4-55.4)*(PM25 - 55.4) + 151), "Unhealthy"),
#       PM25 <= 250.4 ~
#         paste(round((300-201)/(250.4-150.4)*(PM25 - 150.4) + 201), "Very Unhealthy"),
#       TRUE ~ 
#         paste(round((500-301)/(500.4-250.5)*(PM25 - 250.5) + 301), "Hazardous")
#     )
#   ) %>% 
#   separate(
#     AQI,
#     into = c("AQI","AQI_Cat"),
#     sep = " ",
#     extra = "merge"
#   ) %>% 
#   mutate(
#     AQI = as.numeric(AQI),
#     AQI_Cat = AQI_Cat %>% factor(levels = c("Good", "Moderate","Moderately Unhealthy","Unhealthy","Very Unhealthy","Hazardous"))
#   )
# 
# saveRDS(smc_sensors_clean,"smc_sensors_clean.rds")

smc_sensors_clean <- readRDS("smc_sensors_clean.rds")

smc_pm25_voronoi <-
  smc_sensors_clean %>%
  filter(location_type == "outside") %>% 
  st_union() %>% 
  st_voronoi() %>% 
  st_cast() %>% 
  st_as_sf() %>% 
  st_intersection(.,st_union(counties("CA") %>% filter(NAME == "San Mateo") %>% st_transform(4326))) %>% 
  st_join(smc_sensors_clean %>% filter(location_type == "outside"))

# smc_places <- places("CA", cb = T) %>%
#  st_centroid() %>%
#  .[counties("CA") %>% filter(NAME == "San Mateo"),] %>%
#   st_drop_geometry() %>%
#   left_join(places("CA", cb = T) %>% select(PLACEFP)) %>%
#   st_as_sf() %>% 
#   filter(NAME %in% c("Belmont", "East Palo Alto", "Foster City", "Redwood City", "San Mateo", "South San Francisco"))
# 
# saveRDS(smc_places, "smc_places.rds")

smc_places <- readRDS("smc_places.rds")

smc_sensors_clean_outside <- smc_sensors_clean %>% 
  filter(location_type == "outside") %>% 
  .[smc_places %>% st_transform(4326), ]

# smc_cbgs <- block_groups("CA","San Mateo", cb = T) %>% 
#   st_transform(4326)
# saveRDS(smc_cbgs, "smc_cbgs.rds")

smc_cbgs <- readRDS("smc_cbgs.rds")

smc_cbg_places <- smc_cbgs %>% 
  .[smc_places %>% st_transform(4326),]

smc_pm25_voronoi_cbg <-
  smc_pm25_voronoi %>% 
  st_intersection(smc_cbg_places) %>% 
  st_make_valid() %>% 
  mutate(
    area = st_area(.) %>% as.numeric()
  ) %>% 
  st_drop_geometry() %>% 
  group_by(GEOID) %>% 
  summarize(
    PM25 = weighted.mean(PM25, area, na.rm = T)
  ) %>% 
  left_join(smc_cbg_places %>% dplyr::select(GEOID)) %>% 
  st_as_sf()

## getting purple air data by week
# ssf_boundary <- places("CA", cb = T) %>% 
#   filter(NAME == "South San Francisco") %>% 
#   st_transform(4326)
# 
# ssf_sensors <- smc_sensors_clean %>% 
#   .[ssf_boundary,]
# 
# week_start <- c("01", "08","15", "22")
# 
# sensor_daily_ssf <- week_start %>% 
#    map_dfr(function(week_start){
# 
#     start <- paste0("2022-02-", week_start, "%2000:08:00")
#     
#     week_end <- as.character(as.numeric(week_start) + 6) %>% 
#         str_pad(2, side = c("left"), pad = "0")
#     
#     end <- paste0("2022-02-", week_end, "%2000:08:00")
# 
#     print(start)
#     print(end)
#     
#     sensor_data <- 
#       1:nrow(ssf_sensors) %>% 
#       map_dfr(function(row){
#       
#       print(paste0(row,". ",ssf_sensors[row,]$sensor_index))
#       
#       a1 <- read_csv(paste0(
#         "https://api.thingspeak.com/channels/",
#         ssf_sensors[row,]$primary_id_a,
#         "/feeds.csv?api_key=",
#         ssf_sensors[row,]$primary_key_a,
#         "&average=1440&round=3&start=",start,
#         "&end=", end, 
#         "&timezone=America/Los_Angeles"
#       ), show_col_types = F) %>% 
#         set_names(c("created_at","PM1.0_CF_1_ug/m3_A","PM2.5_CF_1_ug/m3_A","PM10.0_CF_1_ug/m3_A","Uptime_Minutes_A","RSSI_dbm_A","Temperature_F_A","Humidity_%_A","PM2.5_CF_ATM_ug/m3_A")
#       ) %>% 
#     transmute(
#       date = as.Date(created_at),
#       ID = as.numeric(ssf_sensors[row,]$sensor_index),
#       Location = ssf_sensors[row,]$location_type,
#       PM25 = 0.524*as.numeric(`PM2.5_CF_1_ug/m3_A`) - 0.0852*as.numeric(`Humidity_%_A`) + 5.72
#     )
#           
#     }) %>% 
#       group_by(date, Location) %>% 
#       summarize(
#         PM25 = mean(PM25, na.rm = T)
#       ) %>% 
#       mutate(
#         city = "South San Francisco"
#       )
#   
#     return(sensor_data)
# })
# 
# full_sensor_ssf <- sensor_daily_ssf %>% filter(Location %in% c("outside"))
# full_sensor_epa <- readRDS("/Users/Chris/Documents/GitHub/chriscobedo.github.io/Winter/sensors/epa_sensor_data.rds")
# full_sensor_fc <- readRDS("/Users/Chris/Documents/GitHub/chriscobedo.github.io/Winter/sensors/fc_sensor_data.rds")
# full_sensor_belmont <- readRDS("/Users/Chris/Documents/GitHub/chriscobedo.github.io/Winter/sensors/feb_daily_belmont_data.rds")
# full_sensor_rwc <- readRDS("/Users/Chris/Documents/GitHub/chriscobedo.github.io/Winter/sensors/rwc_outdoor_weighted.rds")
# full_sensor_sm <- readRDS(
#   "/Users/Chris/Documents/GitHub/chriscobedo.github.io/Winter/sensors/sm_outdoor_weighted.rds"
#   ) %>% 
#   mutate(
#     city = "San Mateo"
#   )
# 
# daily_outdoor_sensor_combined <- full_sensor_belmont %>%
#   bind_rows(full_sensor_epa, full_sensor_fc, full_sensor_rwc, full_sensor_sm, full_sensor_ssf)
# 
# saveRDS(daily_outdoor_sensor_combined,"daily_outdoor_sensor_combined.rds")

daily_outdoor_sensor_combined <- readRDS("daily_outdoor_sensor_combined.rds")


## PART 2 - EQUITY
## income
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

smc_income <-
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*",
    regionin = "state:06+county:081",
    vars = "group(B19001)"
  ) %>%
  mutate(
    GEOID = paste0(state,county,tract,block_group)
  ) %>%
  select(!c(county,tract,block_group,GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>%
      select(name, label)
  ) %>%
  select(-name) %>%
  separate(
    label,
    into = c(NA,NA,"income"),
    sep = "!!"
  ) %>%
  filter(!is.na(income)) %>%
  filter(GEOID %in% smc_cbgs$GEOID) %>%
  left_join(smc_pm25_voronoi_cbg %>%
    select(GEOID, PM25)
  ) %>%
  mutate(
    bucket = as.character(round(PM25)),
    income = case_when(income %in% c("Less than $10,000", "$10,000 to $14,999") ~ "Less than $15,000",
                       income %in% c("$15,000 to $19,999", "$20,000 to $24,999") ~ "$15,000-24,999",
                       income %in% c("$25,000 to $29,999", "$30,000 to $34,999") ~ "$25,000-34,999",
                       income %in% c("$35,000 to $39,999", "$40,000 to $44,999") ~ "$35,000-44,999",
                       income %in% c("$45,000 to $49,999", "$50,000 to $59,999") ~ "$45,000-59,999",
                       income %in% c("$60,000 to $74,999") ~ "$60,000-74,999",
                       income %in% c("$75,000 to $99,999") ~ "$75,000-99,999",
                       income %in% c("$100,000 to $124,999") ~ "$100,000-124,999",
                       income %in% c("$125,000 to $149,999") ~ "$125,000-149,999",
                       income %in% c("$150,000 to $199,999") ~ "$150,000-199,999",
                       income %in% c("$200,000 or more") ~ "$200,000 or more"
                       )
  )

smc_income_total <-
  smc_income %>%
  group_by(income) %>%
  summarize(estimate = sum(as.numeric(estimate))) %>%
  mutate(bucket = "Total")

smc_income_plot <- smc_income %>%
  group_by(bucket, income) %>%
  summarize(estimate = sum(as.numeric(estimate))) %>%
  rbind(smc_income_total) %>%
  ggplot() +
  geom_bar(
    aes(
      x = bucket %>% factor(levels = rev(c("Total", "0", "1","2","3","4","5","6","7","8","9","11"))),
      y = estimate,
      fill = income %>% factor(levels = rev(unique(smc_income$income)))
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "PM25",
    y = "Proportion of Households",
    title = "San Mateo County PM2.5 exposure by Income",
    fill = "Income"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )


## race 
dec_vars_2020 <- read_csv("DECENNIALPL2020.P1_metadata.csv")

names(dec_vars_2020) <- dec_vars_2020[1,]

dec_vars_2020 <- dec_vars_2020 [2:10,] %>%
   mutate(
    name = NAME,
    label = `Geographic Area Name`
   )

smc_race <- read_csv("DECENNIALPL2020.SMC.csv") %>%
  .[-1,] %>%
  select(!c(NAME)) %>%
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>%
    select(name, label)
  ) %>%
  filter(!is.na(label)) %>%
  select(-name) %>%
  separate(
    label,
    into = c(NA,NA,"multiple","race"),
    sep = "!!"
  ) %>%
  mutate(
    race = if_else(is.na(race) & multiple == 'Population of two or more races:',
      'two or more races',
      race
    )
  ) %>%
  filter(!is.na(race)) %>%
  mutate(
    GEOID = str_remove_all(GEO_ID, "1500000US")
  ) %>%
  select(-c(GEO_ID, multiple)) %>%
  filter(GEOID %in% smc_cbgs$GEOID) %>%
  left_join(smc_pm25_voronoi_cbg %>%
    select(GEOID, PM25)
  ) %>%
  mutate(
    bucket = as.character(round(PM25))
  )

smc_race_total <-
  smc_race %>%
  group_by(race) %>%
  summarize(estimate = sum(as.numeric(estimate))) %>%
  mutate(bucket = "Total")

smc_race_plot <- smc_race %>%
  group_by(bucket, race) %>%
  summarize(estimate = sum(as.numeric(estimate))) %>%
  rbind(smc_race_total) %>%
  ggplot() +
  geom_bar(
    aes(
      x = bucket %>% factor(levels = rev(c("Total", "0", "1","2","3","4","5","6","7","8","9","11"))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(smc_race$race)))
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "PM2.5",
    y = "Proportion of Households",
    title = "San Mateo County PM2.5 exposure by Race",
    fill = "Race"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )
```

Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
  inputId = "city", 
  label = "Jurisdiction:",
  choices = c(smc_places$NAME), 
  selected = "Redwood City"
)

selectInput(
  inputId = "equity", 
  label = "Pick a type of equity analysis:",
  choices = c("Income", "Race"), 
  selected = "Income"
)
```

Row
-------------------------------------

### Outdoor average PM2.5 by jurisdiction in San Mateo County for February

```{r}
plotlyOutput("plot")
```

```{r, context = "server"}
observeEvent(input$city, {
  
  cities <- c(input$city)
  
  chart <- daily_outdoor_sensor_combined %>% 
    filter(city %in% cities) %>% 
    ggplot(
      aes(
        x = date,
        y = PM25
      )
    ) +
    geom_point(
    ) +
    geom_line(
      aes(
        color = city %>% factor()
      )
    ) +
    labs(
      x = "",
      y = "PM2.5",
      title = 
        paste0("Daily Average PM2.5 for February"),
      color = "City"
    ) + 
    theme(
      legend.position = "bottom"
    )
  
  output$plot <- renderPlotly({
    chart %>% 
      ggplotly() %>% 
      config(displayModeBar = F)
  })
  
})
```

Row
-------------------------------------

### Map of PM2.5 by CBG averaged using voronoi technique.

```{r}
leafletOutput("map")
```

```{r, context = "server"}
pm25_pal <- colorNumeric(
  palette = "RdYlGn",
  reverse = T,
  domain = c(
    smc_pm25_voronoi_cbg$PM25,
    smc_sensors_clean_outside$PM25
  )
)
  
output$map <- renderLeaflet({
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = smc_pm25_voronoi_cbg,
    fillColor = ~pm25_pal(PM25),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~PM25,
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addCircleMarkers(
    data = smc_sensors_clean_outside,
    fillColor = ~pm25_pal(PM25),
    fillOpacity = 1,
    color = "black",
    weight = 0.5,
    radius = 5,
    label = ~PM25
  ) %>% 
  addLegend(
    pal = pm25_pal,
    values = c(
      smc_pm25_voronoi_cbg$PM25,
      smc_sensors_clean_outside$PM25
    ),
    title = "Weekly Average PM2.5<br>for 3/16 by CBG"
  )
})
```

```{r, context = "server"}
observeEvent(input$city, {
  
  cities <- c(input$city) 
  
  selected <- smc_places %>% 
    filter(NAME %in% c(input$city))
  
  leafletProxy("map") %>% 
    removeShape("selected") %>% 
    addPolygons(
      data = smc_places %>% filter(NAME %in% c(input$city)),
      fill = F,
      color = "black",
      weight = 2,
      opacity = 1,
      layerId = "selected"
    )
  
})
```

### PM2.5 Equity Analysis for San  Mateo County

```{r}
plotlyOutput("equity_plot")
```

```{r, context = "server"}
observeEvent(input$equity, {

  if(input$equity == "Income"){
    chart <- smc_income_plot
  } else {
    chart <- smc_race_plot
  }

  output$equity_plot <- renderPlotly({
    chart %>%
      ggplotly() %>%
      config(displayModeBar = F)
  })

})
```













