---
title: "Class 1"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document  
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(tidycensus)
library(esri2sf)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

```{r}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

pums_vars_2019 <- 
  pums_variables %>%
  filter(year == 2019, survey == "acs5")
```

```{r}
census_api_key("c7ce771b506b13ca6875d12a179606f8087fa381", install = TRUE)

ca_pums <- get_pums(
  variables = c(
    "PUMA",
    "GRNTP",
    "SMOCP",
    "ADJHSG",
    "HINCP",
    "ADJINC"
  ),
  state = "CA",
  year = 2019,
  survey = "acs5"
)

bay_pums <-
  ca_pums %>% 
  filter(PUMA %in% bay_pumas$PUMACE10)

```

stats
```{r}
burden_threshold <- 0.3

bay_burden <-
  bay_pums %>% 
  filter(HINCP > 0) %>%
  filter(SPORDER == 1) %>% 
  transmute(
    PUMA,
    weight = WGTP,
    housingcost = ifelse(
      SMOCP > 0,
      SMOCP*12*as.numeric(ADJHSG),
      GRNTP*12*as.numeric(ADJHSG)
    ),
    income = HINCP*as.numeric(ADJINC),
    burden_perc = housingcost/income,
    burden = housingcost - burden_threshold*income
  )

bay_burden_pumas <-
  bay_burden %>% 
  mutate(
    burdened = ifelse(
      burden_perc >= burden_threshold,
      weight,
      0
    ),
    excess = ifelse(
      burden < 0,
      burden,
      0
    ),
    burden = ifelse(
      burden > 0,
      burden,
      0
    )
  ) %>% 
  group_by(PUMA) %>% 
  summarize(
    burdened = sum(burdened),
    households = sum(weight),
    burden = sum(burden*weight),
    excess = sum(excess*weight)
  ) %>% 
  mutate(
    burdened_perc = burdened/households
  ) %>% 
  left_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()

sum(bay_burden_pumas$burdened)/sum(bay_burden_pumas$households)

sum(bay_burden_pumas$burden) %>% prettyNum(",") %>% paste0("$",.)
```

Maps
```{r}
burden_pal1 <- colorNumeric(
  palette = "Purples",
  domain = bay_burden_pumas$burdened_perc
)

bay_burden_pumas %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = ~burden_pal1(burdened_perc),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0(round(burdened_perc*100), "% of households paying 30%+ of income on housing"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal1,
    values = ~burdened_perc,
    title = "% Cost-burdened<br>households"
  )

burden_pal2 <- colorNumeric(
  palette = "Reds",
  domain = bay_burden_pumas$burden/1e6
)

bay_burden_pumas %>% 
  leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    fillColor = ~burden_pal2(burden/1e6),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0("$", round(burden/1e6), "M total annual cost burden"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal2,
    values = ~burden/1e6,
    title = "Total housing cost<br>burden, in $ millions"
  )
```





