---
title: "equity"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```


```{r}
smc_pm25_voronoi

smc_pm25_voronoi_cbg <-
  smc_pm25_voronoi %>% 
  st_intersection(smc_cbgs) %>% 
  st_make_valid() %>% 
  mutate(
    area = st_area(.) %>% as.numeric()
  ) %>% 
  st_drop_geometry() %>% 
  group_by(GEOID) %>% 
  summarize(
    PM25 = weighted.mean(PM25, area, na.rm = T)
  ) %>% 
  left_join(smc_cbgs %>% dplyr::select(GEOID)) %>% 
  st_as_sf()

# # income
# smc_income <-
#   getCensus(
#     name = "acs/acs5",
#     vintage = 2019,
#     region = "block group:*",
#     regionin = "state:06+county:081",
#     vars = "group(B19001)"
#   ) %>%
#   mutate(
#     GEOID = paste0(state,county,tract,block_group)
#   ) %>%
#   select(!c(county,tract,block_group,GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
#   pivot_longer(
#     ends_with("E"),
#     names_to = "name",
#     values_to = "estimate"
#   ) %>%
#   left_join(
#     acs_vars_2019_5yr %>%
#       select(name, label)
#   ) %>%
#   select(-name) %>%
#   separate(
#     label,
#     into = c(NA,NA,"income"),
#     sep = "!!"
#   ) %>%
#   filter(!is.na(income)) %>%
#   filter(GEOID %in% smc_cbgs$GEOID) %>%
#   left_join(smc_pm25_voronoi_cbg %>%
#     select(GEOID, PM25)
#   ) %>%
#   mutate(
#     bucket = as.character(round(PM25)),
#     income = case_when(income %in% c("Less than $10,000", "$10,000 to $14,999") ~ "Less than $15,000",
#                        income %in% c("$15,000 to $19,999", "$20,000 to $24,999") ~ "$15,000-24,999",
#                        income %in% c("$25,000 to $29,999", "$30,000 to $34,999") ~ "$25,000-34,999",
#                        income %in% c("$35,000 to $39,999", "$40,000 to $44,999") ~ "$35,000-44,999",
#                        income %in% c("$45,000 to $49,999", "$50,000 to $59,999") ~ "$45,000-59,999",
#                        income %in% c("$60,000 to $74,999") ~ "$60,000-74,999",
#                        income %in% c("$75,000 to $99,999") ~ "$75,000-99,999",
#                        income %in% c("$100,000 to $124,999") ~ "$100,000-124,999",
#                        income %in% c("$125,000 to $149,999") ~ "$125,000-149,999",
#                        income %in% c("$150,000 to $199,999") ~ "$150,000-199,999",
#                        income %in% c("$200,000 or more") ~ "$200,000 or more"
#                        )
#   )
# 
# smc_income_total <-
#   smc_income %>%
#   group_by(income) %>%
#   summarize(estimate = sum(as.numeric(estimate))) %>%
#   mutate(bucket = "Total")
# 
# smc_income_plot <- smc_income %>%
#   group_by(bucket, income) %>%
#   summarize(estimate = sum(as.numeric(estimate))) %>%
#   rbind(smc_income_total) %>%
#   ggplot() +
#   geom_bar(
#     aes(
#       x = bucket %>% factor(levels = rev(c("Total", "0", "1","2","3","4","5","6","7","8","9","11"))),
#       y = estimate,
#       fill = income %>% factor(levels = rev(unique(smc_income$income)))
#     ),
#     stat = "identity",
#     position = "fill"
#   ) +
#   labs(
#     x = "PM25",
#     y = "Proportion of Households",
#     title = "San Mateo County PM2.5 exposure by Income",
#     fill = "Income"
#   ) +
#   coord_flip() +
#   theme(
#     legend.position = "bottom",
#     legend.direction = "vertical"
#   )  +
#   guides(
#     fill = guide_legend(
#       reverse = T
#     )
#   )
# 
# saveRDS(smc_income_plot, "smc_income_plot.rds")

smc_income_plot <- readRDS("smc_income_plot.rds")


## race 
# dec_vars_2020 <- read_csv("DECENNIALPL2020.P1_metadata.csv")
# 
# names(dec_vars_2020) <- dec_vars_2020[1,]
# 
# dec_vars_2020 <- dec_vars_2020 [2:10,] %>% 
#    mutate(
#     name = NAME,
#     label = `Geographic Area Name`
#    )
# 
# smc_race <- smc_race %>% 
#   left_join(smc_cbgs) %>% 
#   st_as_sf()
# 
# smc_race <- read_csv("DECENNIALPL2020.SMC.csv") %>% 
#   .[-1,] %>% 
#   select(!c(NAME)) %>%
#   pivot_longer(
#     ends_with("N"),
#     names_to = "name",
#     values_to = "estimate"
#   ) %>% 
#   left_join(
#     dec_vars_2020 %>% 
#     select(name, label)
#   ) %>% 
#   filter(!is.na(label)) %>% 
#   select(-name) %>% 
#   separate(
#     label,
#     into = c(NA,NA,"multiple","race"),
#     sep = "!!"
#   ) %>% 
#   mutate(
#     race = if_else(is.na(race) & multiple == 'Population of two or more races:',
#       'two or more races',
#       race
#     )
#   ) %>% 
#   filter(!is.na(race)) %>% 
#   mutate(
#     GEOID = str_remove_all(GEO_ID, "1500000US")
#   ) %>%
#   select(-c(GEO_ID, multiple)) %>%
#   filter(GEOID %in% smc_cbgs$GEOID) %>% 
#   left_join(smc_pm25_voronoi_cbg %>% 
#     select(GEOID, PM25)
#   ) %>%
#   mutate(
#     bucket = as.character(round(PM25))
#   )
# 
# smc_race_total <-
#   smc_race %>% 
#   group_by(race) %>% 
#   summarize(estimate = sum(as.numeric(estimate))) %>%
#   mutate(bucket = "Total")
# 
# smc_race_plot <- smc_race %>% 
#   group_by(bucket, race) %>% 
#   summarize(estimate = sum(as.numeric(estimate))) %>% 
#   rbind(smc_race_total) %>% 
#   ggplot() +
#   geom_bar(
#     aes(
#       x = bucket %>% factor(levels = rev(c("Total", "0", "1","2","3","4","5","6","7","8","9","11"))),
#       y = estimate,
#       fill = race %>% factor(levels = rev(unique(smc_race$race)))
#     ),
#     stat = "identity",
#     position = "fill"
#   ) +
#   labs(
#     x = "PM25",
#     y = "Proportion of Households",
#     title = "San Mateo County PM2.5 exposure by Race",
#     fill = "Race"
#   ) +
#   coord_flip() +
#   theme(
#     legend.position = "bottom",
#     legend.direction = "vertical"
#   )  +
#   guides(
#     fill = guide_legend(
#       reverse = T
#     )
#   )
#   
# saveRDS(smc_race_plot, "smc_race_plot.rds")

smc_race_plot <- readRDS("smc_race_plot.rds")
```