---
title: "Chapter_5"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

```{r}
bay_education_income_tract <- 
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "tract:*",
    regionin = "state:06+county:001,013,041,055,075,081,085,095,097",
    vars = c(
      "B06009_001E",
      "B06009_002E",
      "B06009_003E",
      "B19001_001E",
      "B19001_014E",
      "B19001_015E",
      "B19001_016E",
      "B19001_017E"
    )
  ) %>% 
  transmute(
    tract = paste0(state, county, tract),
    perc_college = 1 - (B06009_002E + B06009_003E) / B06009_001E,
    perc_over100k = (B19001_014E + B19001_015E + B19001_016E + B19001_017E) / B19001_001E
  ) %>% 
  filter(
    !is.na(perc_college), 
    !is.na(perc_over100k)
  )

ggplot() +
  geom_point(
    data = bay_education_income_tract,
    aes(
      x = perc_college,
      y = perc_over100k
    )
  )

ggplot(
  data = bay_education_income_tract,
  aes(
      x = perc_college,
      y = perc_over100k
    )
) +
  geom_point() +
  geom_smooth(method = "lm")

```

calculating own best fit line
```{r}
slope <- 0
yintercept <- mean(bay_education_income_tract$perc_over100k)

best_fit_candidate <- slope * bay_education_income_tract$perc_college + yintercept

residuals <- bay_education_income_tract$perc_over100k - best_fit_candidate

sumsq_residuals <- sum(residuals^2)

sumsq_residuals

ggplot(
  data = bay_education_income_tract,
  aes(
      x = perc_college,
      y = perc_over100k
    )
) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_line(
    aes(
      x = bay_education_income_tract$perc_college,
      y = best_fit_candidate
    ),
    color = "red",
    size = 1
  )
```

creating a function to calculate SSR (sum of squared residuals)
```{r}
get_sumsq_residuals <- function(x){

  slope <- x[1]
  yintercept <- x[2]
  
  best_fit_candidate <- slope * bay_education_income_tract$perc_college + yintercept 
  
  residuals <- bay_education_income_tract$perc_over100k - best_fit_candidate
  
  sumsq_residuals <- sum(residuals^2)
}

```


```{r}

```









