---
title: "ChrisEscobedo_A6"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r, include = F}
library(tidyverse)
library(mapview)
library(sf)
library(leaflet)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```

## Map of San Francisco PUMAS

```{r}
mapview(sf_pumas)
```

There are a few geographical anomalies that appear on this map, including part of Angel Island, a sliver of Alameda, and the Farallon Islands. These will be ignored as they will not affect the analysis.

```{r}
pums_2019_1yr <- getCensus(
   name = "acs/acs1/pums",
   vintage = 2019,
   region = "public use microdata area:*",
   regionin = "state:06",
   vars = c(
     "SERIALNO",
     "SPORDER",
     "PWGTP",
     "WGTP",
     "YBL",
     "BLD",
     "TEN",
     "MV",
     "HINCP",
     "AGEP"
   )
 )
saveRDS(pums_2019_1yr, "a6_pums.rds")
```

```{r}
sf_pums <- pums_2019_1yr %>% 
  mutate (
    PUMA = str_pad(public_use_microdata_area, 5, "left", "0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)

sf_pums_1960 <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP= as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3)

sf_pums_clean <- sf_pums_1960 %>% 
  group_by()
  
sf_pums_lead_risk <- sf_pums_clean %>% 
  mutate(
    leadrisk = 
      (ifelse(
        HINCP < 90000 & AGEP < 6,
        1,
        0
        )
      )
  )

```













