---
title: "ChrisEscobedo_A9"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(plotly)
pge_data_raw <- readRDS("pge_data_raw.rds")
bay_zips <- readRDS("bay_zips.rds")
pge_data <-
  pge_data_raw %>% 
  filter(
    CUSTOMERCLASS %in% c(
      "Elec- Commercial",
      "Elec- Residential",
      "Gas- Commercial",
      "Gas- Residential"
    )
  ) %>% 
  group_by(
    MONTH, 
    YEAR, 
    CUSTOMERCLASS
  ) %>% 
  summarize(
    TOTALKBTU = sum(TOTALKBTU, na.rm = T)
  ) %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )
```

Inputs {.sidebar}
-------------------------------------

```{r}
# selectInput(
#   inputId = "year",
#   label = "Year:",
#   choices = c(2017,2018,2019,2020),
#   selected = 2020
# )

checkboxGroupInput(
  inputId = "year",
  label = "Year:",
  choices = c(2017,2018,2019,2020),
  selected = 2020,
)

selectInput(
  inputId = "customerclass",
  label = "Customer Class:",
  choices = c("Elec- Residential","Elec- Commercial", "Gas- Residential", "Gas- Commercial"),
  selected = "Elec- Residential",
)

```

Column
-------------------------------------

### Monthly consumption

```{r} 
plotlyOutput("plot")
```

```{r, context = "server"}
observeEvent({
  input$year
  input$customerclass
  }, {

  chart <- pge_data %>% 
    filter(
      CUSTOMERCLASS == input$customerclass,
      if(length(input$year) == 0){
        YEAR == 2020
      } else {
        YEAR %in% c(input$year)
      }
    ) %>% 
    ggplot(
      aes(
        x = MONTH,
        y = TOTALKBTU/1e9,
      )
    ) +
    geom_line(
      aes(
        color = YEAR %>% factor()
      )
    ) +
    scale_x_discrete(
      limits = c(
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec"
      )
    ) +
    labs(
      x = "",
      y = "Total kBTUs (billions)",
      title = paste0("Residential Energy Consumption in the Bay Area, ", input$year),
      color = "Year"
    ) + 
    theme(legend.position = "none")
  
  output$plot <- renderPlotly({
    chart %>% 
      ggplotly() %>% 
      config(displayModeBar = F)
  })
  
})
```

Column
-------------------------------------

### ZCTA consumption

```{r}
leafletOutput("map")
```

```{r, context = "server"}
observeEvent({
  input$year
  input$customerclass
  }, {
    
  pge_class <-
    pge_data_raw %>% 
    filter(
      CUSTOMERCLASS == input$customerclass,
       if(length(input$year) == 0){
        YEAR == 2020
      } else {
        YEAR == max(input$year)
      }
    ) %>% 
    mutate(
      ZIPCODE = ZIPCODE %>% as.character()
    ) %>% 
    group_by(ZIPCODE) %>% 
    summarize(
      TOTALKBTU = sum(TOTALKBTU, na.rm = T)
    ) %>% 
    right_join(
      bay_zips %>% select(GEOID10),
      by = c("ZIPCODE" = "GEOID10")
    ) %>% 
    st_as_sf() %>% 
    st_transform(4326)
  
  res_pal <- colorNumeric(
    palette = "Reds",
    domain = 
      pge_class$TOTALKBTU
  )
  
  class_names <- c("Residential Electricity","Commercial Electricity", "Residential Gas", "Commercial Gas") 
  
  class_current <- input$customerclass
  
  class_name_current <- 
    if(input$customerclass == "Elec- Residential"){
      class_names[1]
    } else if(input$customerclass == "Elec- Commercial"){
      class_names[2]
    } else if(input$customerclass == "Gas- Residential"){
      class_names[3]
    } else {
      class_names[4]
    }
  
  output$map <- renderLeaflet({
    leaflet() %>% 
      addProviderTiles(provider = providers$CartoDB.Positron) %>% 
      addPolygons(
        data = pge_class,
        fillColor = ~res_pal(TOTALKBTU),
        color = "white",
        opacity = 0.5,
        fillOpacity = 0.5,
        weight = 1,
        label = ~paste0(
          round(TOTALKBTU), 
          " kBTU total in ",
          ZIPCODE
        ),
        highlightOptions = highlightOptions(
          weight = 2,
          opacity = 1
        )
      ) %>% 
      addLegend(
        data = pge_class,
        pal = res_pal,
        values = ~TOTALKBTU,
        title = 
          if(length(input$year) == 0){
            paste0("Total ",class_name_current,"<br>Consumption (kBTU), 2020")
          } else {
            paste0("Total ",class_name_current,"<br>Consumption (kBTU), ", max(input$year))
        }
      )
  })
  
})
```