---
title: "Chapter_6"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r, include = F}
library(tidyverse)
library(mapview)
library(sf)
library(StatMatch)
library(leaflet)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

```{r}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

```{r}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_tracts <-
  tracts("CA", bay_county_names, cb = T, progress_bar = F)

bay_multiple_tract <- 
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "tract:*",
    regionin = "state:06+county:001,013,041,055,075,081,085,095,097",
    vars = c(
      "B06009_001E",
      "B06009_002E",
      "B06009_003E",
      "B19001_001E",
      "B19001_014E",
      "B19001_015E",
      "B19001_016E",
      "B19001_017E",
      "B19001A_001E"
    )
  ) %>% 
  transmute(
    tract = paste0(state, county, tract),
    perc_college = 1 - (B06009_002E + B06009_003E) / B06009_001E,
    perc_over100k = (B19001_014E + B19001_015E + B19001_016E + B19001_017E) / B19001_001E,
    perc_white = B19001A_001E / B19001_001E
  ) %>% 
  filter(
    !is.na(perc_college), 
    !is.na(perc_over100k),
    !is.na(perc_white)
  )
```

make into matrix form
```{r}
obs_matrix <-
  bay_multiple_tract %>% 
  select(
    perc_white, 
    perc_over100k,
    perc_college
  ) %>% 
  as.matrix()
```

mahalanobis 
```{r}
dist_matrix <- mahalanobis.dist(obs_matrix)

rownames(dist_matrix) <- bay_multiple_tract$tract
colnames(dist_matrix) <- bay_multiple_tract$tract
```

match pairs - closest tract
```{r}
dist_matrix_pairmatch <- dist_matrix

diag(dist_matrix_pairmatch) <- NA

matched_pair_tract <-
  1:nrow(dist_matrix_pairmatch) %>% 
  map_dfr(function(x){
    
    min_index <- which(dist_matrix_pairmatch[x, ] == min(dist_matrix_pairmatch[x, ], na.rm = T))
   
    data.frame(
      tract = bay_multiple_tract$tract[x],
      matched_tract = bay_multiple_tract$tract[min_index]
    )
    
  })

```

map of 20 matches
```{r}
match_set_tract <- dist_matrix["06081611900", ] %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    tract = rowname,
    match = "."
  ) %>% 
  right_join(
    bay_multiple_tract
  ) %>% 
  arrange(match) %>% 
  .[1:21, ] %>% 
  left_join(bay_tracts %>% select(tract = GEOID)) %>% 
  st_as_sf()

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = match_set_tract[1, ],
    color = "red"
  ) %>% 
  addPolygons(
    data = match_set_tract[-1, ]
  )
```

DIFF IN DIFF 6.2

PUMAS
```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = bay_pumas,
    weight = 1,
    color = "gray",
    label = ~PUMACE10
  ) %>% 
  addMarkers(
    lng = -121.9415017,
    lat = 37.502171
  ) %>% 
  addPolygons(
    data = bay_pumas %>% 
      filter(PUMACE10 == "08504")
  )
```

downloading and cleaning PUMS for Bart ridership
```{r}
pums_2014_2019 <-
  2014:2019 %>% 
  map_dfr(function(year){
    
    getCensus(
      name = "acs/acs1/pums",
      vintage = year,
      region = "public use microdata area:*", 
      regionin = "state:06",
      vars = c(
        "SERIALNO",
        "SPORDER",
        ifelse(
          year == 2019,
          "JWTRNS",
          "JWTR"
        ),
        "PWGTP",
        paste0("PWGTP",1:80)
      )
    ) %>% 
      mutate(
        year = year,
        PUMA = public_use_microdata_area %>% str_pad(5,"left","0")
      ) %>% 
      filter(
        PUMA %in% bay_pumas$PUMACE10
      ) %>% 
      rename(
        JWTR = ifelse(
          year == 2019,
          "JWTRNS",
          "JWTR"
        )
      )
    
  })
  
pums_bart <- pums_2014_2019 %>%
  mutate(
    PWGTP = as.numeric(PWGTP),
    bart = ifelse(
      JWTR %in% c("4"),
      PWGTP,
      0
    )
  ) %>% 
  group_by(PUMA, year) %>% 
  summarize(
    pop = sum(PWGTP),
    bart = sum(bart)
  )
```

distribution of population AND bart commuters 
```{r}
pums_pal <- colorNumeric(
  palette = "YlOrRd",
  domain = pums_bart %>% 
    filter(year == 2017) %>% 
    pull(pop)
)

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pums_bart %>% 
      filter(year == 2017) %>% 
      right_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
      st_as_sf(),
    fillColor = ~pums_pal(pop),
    color = "white",
    weight = 1,
    fillOpacity = 0.5,
    label = ~paste0(PUMA,": Population ", pop)
  )

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pums_bart %>% 
      filter(year == 2017) %>% 
      right_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
      st_as_sf(),
    fillColor = ~pums_pal(pop),
    color = "white",
    weight = 1,
    fillOpacity = 0.5,
    label = ~paste0(PUMA,": Population ", pop)
  )
```

years wider and Mahalanobis
```{r}
pums_bart_clean <-
  pums_bart %>% 
  select(-pop) %>% 
  pivot_wider(
    names_from = year,
    values_from = bart
  )

obs_matrix <-
  pums_bart_clean %>% 
  ungroup() %>% 
  select(`2014`,`2015`,`2016`) %>% 
  as.matrix()

dist_matrix <- mahalanobis.dist(obs_matrix)

rownames(dist_matrix) <- pums_bart_clean$PUMA
colnames(dist_matrix) <- pums_bart_clean$PUMA

match <- dist_matrix["08504",] %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    PUMA = rowname,
    match = "."
  ) %>% 
  right_join(
    pums_bart_clean
  ) %>% 
  arrange(match) %>% 
  .[1:11, ] %>% 
  left_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()
```

map of mahalanobis
```{r}
leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = match[1, ],
    color = "red",
    label = ~PUMA
  ) %>% 
  addPolygons(
    data = match[-1, ],
    label = ~PUMA
  )
```

comparing PUMA to matched PUMAS in plot
```{r}
match_pumas <-
  match %>% 
  filter(!PUMA %in% c("08504")) %>% 
  st_drop_geometry() %>% 
  select(-match) %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  ) %>%
  group_by(
    year
  ) %>% 
  summarize(
    bart = mean(bart),
    PUMA = "Similar PUMAs"
  )

treatment_pumas <-
  match %>% 
  filter(PUMA %in% c("08504")) %>% 
  select(-match) %>% 
  st_drop_geometry() %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  )

rbind(
  treatment_pumas,
  match_pumas
) %>% 
  ggplot(
    aes(
      x = as.numeric(year),
      y = bart,
      color = PUMA
    )
  ) +
  geom_line() +
  geom_vline(xintercept = 2017, linetype = "dashed") +
  labs(
    title = "Milpitas vs. control neighborhoods, BART ridership",
    x = "Year",
    y = "BART commute riders"
  )
```

difference in difference regresstion (and tidy data)
```{r}
transit_did <-
  match %>% 
  st_drop_geometry() %>% 
  select(-match) %>% 
  pivot_longer(
    -PUMA,
    names_to = "year",
    values_to = "bart"
  ) %>% 
  mutate(
    year = year %>% as.numeric(),
    time = ifelse(year >= 2017, 1, 0),
    treated = ifelse(PUMA == "08504", 1, 0)
  )

did_reg <- lm(bart ~ treated*time, data = transit_did)

summary(did_reg)
```








