---
title: "ChrisEscobedo_A8"
author: "Chris"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)
```

```{r, include = F}
library(tidyverse)
library(mapview)
library(sf)
library(StatMatch)
library(leaflet)
library(tigris)
library(censusapi)

Sys.setenv(CENSUS_KEY="c7ce771b506b13ca6875d12a179606f8087fa381")
```

```{r}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```

```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```

```{r}
pums_2014_2019_wts <- readRDS("pums_2014_2019_wts.rds") 

pums_bart <- pums_2014_2019_wts %>%
  mutate(
    PWGTP = as.numeric(PWGTP),
    bart = ifelse(
      JWTR %in% c("4"),
      PWGTP,
      0
    )
  ) %>% 
  group_by(PUMA, year) %>% 
  summarize(
    pop = sum(PWGTP),
    bart = sum(bart)
  )

pums_bart_clean <-
  pums_bart %>% 
  select(-pop) %>% 
  pivot_wider(
    names_from = year,
    values_from = bart
  )

obs_matrix <-
  pums_bart_clean %>% 
  ungroup() %>% 
  select(`2014`,`2015`,`2016`,`2017`) %>% 
  as.matrix()

dist_matrix <- mahalanobis.dist(obs_matrix)

rownames(dist_matrix) <- pums_bart_clean$PUMA
colnames(dist_matrix) <- pums_bart_clean$PUMA

match <- dist_matrix["01309",] %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    PUMA = rowname,
    match = "."
  ) %>% 
  right_join(
    pums_bart_clean
  ) %>% 
  arrange(match) %>% 
  .[1:11, ] %>% 
  left_join(bay_pumas %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()
```

## Map of Matched PUMAS
```{r}
leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = match[1, ],
    color = "red",
    label = ~PUMA
  ) %>% 
  addPolygons(
    data = match[-1, ],
    label = ~PUMA
  )
```









